name: Nuevo Cliente Creado

on:
  workflow_dispatch:
    inputs:
      nombre_cliente:
        description: 'Nombre del Cliente'
        required: true

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir notificaci√≥n
        run: |
          echo "[NUEVO CLIENTE CREADO] Nombre: ${{ github.event.inputs.nombre_cliente }}. Notificando a DevTeam, ITTeam, CustServTeam."
